import { brand, neutral } from "@/constants/Colors";
import { fontFamily, fontSize } from "@/constants/Typography";
import {
    StyleSheet,
} from "react-native";


export const s = StyleSheet.create({
    root: { flex: 1, backgroundColor: "#fff" },

    // Header
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: neutral[100],
    },
    headerBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
    },
    headerTitle: {
        fontFamily: fontFamily.semibold,
        fontSize: fontSize.sm,
        color: neutral[800],
    },
    headerSub: {
        fontFamily: fontFamily.regular,
        fontSize: fontSize.xs,
        color: neutral[400],
        marginTop: 1,
    },

    // Choose — VibeTag preview
    vibePreview: {
        flex: 1,
        backgroundColor: neutral[100],
        overflow: "hidden",
        position: "relative",
    },
    vibePreviewGrad: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        height: 120,
        backgroundColor: "rgba(0,0,0,0.45)",
    },
    vibePreviewInfo: {
        position: "absolute",
        bottom: 16,
        left: 16,
        right: 16,
        gap: 6,
    },
    vibeChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        alignSelf: "flex-start",
        backgroundColor: "rgba(255,255,255,0.2)",
        borderRadius: 20,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.3)",
    },
    vibeChipText: {
        fontFamily: fontFamily.semibold,
        fontSize: 12,
        color: "#fff",
    },
    vibePreviewHint: {
        fontFamily: fontFamily.regular,
        fontSize: 12,
        color: "rgba(255,255,255,0.75)",
    },
    vibePreviewEmpty: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        padding: 24,
    },
    vibePreviewEmptyIcon: {
        width: 72,
        height: 72,
        borderRadius: 22,
        backgroundColor: `${brand.primary}12`,
        alignItems: "center",
        justifyContent: "center",
    },
    vibePreviewEmptyTitle: {
        fontFamily: fontFamily.semibold,
        fontSize: fontSize.lg,
        color: neutral[700],
    },
    vibePreviewEmptySub: {
        fontFamily: fontFamily.regular,
        fontSize: fontSize.sm,
        color: neutral[400],
        textAlign: "center",
    },

    // Choose — action buttons
    chooseActions: {
        padding: 16,
        gap: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: neutral[100],
    },
    cameraBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        backgroundColor: brand.primary,
        borderRadius: 16,
        padding: 16,
    },
    cameraBtnIcon: {
        width: 46,
        height: 46,
        borderRadius: 14,
        backgroundColor: "rgba(255,255,255,0.15)",
        alignItems: "center",
        justifyContent: "center",
    },
    cameraBtnTitle: {
        fontFamily: fontFamily.semibold,
        fontSize: fontSize.sm,
        color: "#fff",
    },
    cameraBtnSub: {
        fontFamily: fontFamily.regular,
        fontSize: 11,
        color: "rgba(255,255,255,0.7)",
        marginTop: 2,
    },
    galleryBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        backgroundColor: `${brand.primary}08`,
        borderRadius: 16,
        padding: 16,
        borderWidth: 1.5,
        borderColor: `${brand.primary}18`,
    },
    galleryBtnIcon: {
        width: 46,
        height: 46,
        borderRadius: 14,
        backgroundColor: `${brand.primary}12`,
        alignItems: "center",
        justifyContent: "center",
    },
    galleryBtnTitle: {
        fontFamily: fontFamily.semibold,
        fontSize: fontSize.sm,
        color: neutral[800],
    },
    galleryBtnSub: {
        fontFamily: fontFamily.regular,
        fontSize: 11,
        color: neutral[400],
        marginTop: 2,
    },

    // VibeTag banner in review
    vibeBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 14,
        paddingVertical: 7,
        backgroundColor: `${brand.primary}06`,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: `${brand.primary}18`,
    },
    vibeBannerText: {
        fontFamily: fontFamily.semibold,
        fontSize: 12,
        color: brand.primary,
        flex: 1,
    },
    vibeBannerSub: {
        fontFamily: fontFamily.regular,
        fontSize: 11,
        color: neutral[400],
    },

    // Bug 1 fix: preview container uses 9:16 portrait ratio to match the
    // 1080×1920 composited output dimensions, so the overlay is not zoomed.
    mediaPreview: {
        width: "100%",
        aspectRatio: 9 / 16,
        backgroundColor: "#000",
        position: "relative",
        overflow: "hidden",
    },
    overlayBadge: {
        position: "absolute",
        bottom: 12,
        left: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: "rgba(0,0,0,0.55)",
        borderRadius: 20,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.25)",
    },
    overlayBadgeText: {
        fontFamily: fontFamily.semibold,
        fontSize: 11,
        color: "#fff",
        maxWidth: 180,
    },
    removeBtn: {
        position: "absolute",
        top: 12,
        right: 12,
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: "rgba(0,0,0,0.6)",
        alignItems: "center",
        justifyContent: "center",
    },
    counterBadge: {
        position: "absolute",
        top: 12,
        left: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: "rgba(0,0,0,0.55)",
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    counterBadgeText: {
        fontFamily: fontFamily.semibold,
        fontSize: 11,
        color: "#fff",
    },

    // Thumbnail strip
    thumbStrip: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        gap: 8,
        flexDirection: "row",
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: neutral[100],
    },
    thumb: {
        width: 52,
        height: 52,
        borderRadius: 10,
        overflow: "hidden",
        backgroundColor: neutral[100],
        borderWidth: 2.5,
        borderColor: "transparent",
    },
    thumbSelected: { borderColor: brand.primary },
    thumbVideo: {
        flex: 1,
        backgroundColor: "#111",
        alignItems: "center",
        justifyContent: "center",
    },
    thumbRemove: { position: "absolute", top: 1, right: 1 },
    thumbAddWrap: {
        width: 52,
        height: 52,
        borderRadius: 10,
        borderWidth: 1.5,
        borderStyle: "dashed",
        borderColor: neutral[300],
        overflow: "hidden",
    },
    thumbAdd: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: neutral[200],
    },

    // Caption
    captionSection: {
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: neutral[100],
    },
    captionInput: {
        fontFamily: fontFamily.regular,
        fontSize: fontSize.sm,
        color: neutral[800],
        minHeight: 62,
        textAlignVertical: "top",
        paddingVertical: 0,
    },
    captionCount: {
        fontFamily: fontFamily.regular,
        fontSize: fontSize.xs,
        color: neutral[300],
        textAlign: "right",
        marginTop: 4,
    },

    // Post section
    postSection: { padding: 14, gap: 10 },
    progressCard: {
        backgroundColor: neutral[50],
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: neutral[200],
    },
    progressLabel: {
        fontFamily: fontFamily.semibold,
        fontSize: fontSize.sm,
        color: neutral[700],
    },
    progressPct: {
        fontFamily: fontFamily.bold,
        fontSize: fontSize.sm,
        color: brand.primary,
    },
    progressTrack: {
        height: 6,
        borderRadius: 3,
        backgroundColor: neutral[200],
        overflow: "hidden",
    },
    progressFill: {
        height: "100%",
        backgroundColor: brand.primary,
        borderRadius: 3,
    },
    progressSub: {
        fontFamily: fontFamily.regular,
        fontSize: fontSize.xs,
        color: neutral[400],
        marginTop: 6,
    },
    postBtn: {
        height: 54,
        borderRadius: 16,
        backgroundColor: brand.primary,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
    },
    postBtnText: {
        fontFamily: fontFamily.bold,
        fontSize: fontSize.sm,
        color: "#fff",
        letterSpacing: 0.2,
    },
    startOverBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
        paddingVertical: 4,
    },
    startOverText: {
        fontFamily: fontFamily.regular,
        fontSize: fontSize.sm,
        color: neutral[400],
    },
});
